version: '3.7'

services:
  node_backend:
    container_name: node_backend
    image: node:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    environment:
      - EXTERNAL_PORT=8080
      - PGUSER=ivan
      - PGPASSWORD=12345
      - PGDATABASE=defaultdb
      - PGHOST=db
    command: npm run dev
    depends_on:
      - db

  db:
    container_name: db
    image: 'postgres:12'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=ivan
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=defaultdb
    volumes:
      - pgdata1:/var/lib/postgresql/data

volumes:
  pgdata1: {}
